// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace VinculacionBackend.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class FacultiesReportsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "FacultiesReports.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "FacultiesReports", "\tIn order to know the value each faculty has given to the community\r\n\tAs manager\r" +
                    "\n\tI want to be told the costs of each faculty", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "FacultiesReports")))
            {
                VinculacionBackend.Specs.FacultiesReportsFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Costs report by faculties")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "FacultiesReports")]
        public virtual void CostsReportByFaculties()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Costs report by faculties", ((string[])(null)));
#line 6
 this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name"});
            table1.AddRow(new string[] {
                        "1",
                        "Ingenieria"});
            table1.AddRow(new string[] {
                        "2",
                        "Licenciatura"});
#line 7
 testRunner.Given("I have this faculties", ((string)(null)), table1, "Given ");
#line 11
 testRunner.And("the year is 2015", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "FacultyName",
                        "ProjectCost"});
            table2.AddRow(new string[] {
                        "Ingenieria",
                        "30"});
            table2.AddRow(new string[] {
                        "Ingenieria",
                        "10"});
#line 12
 testRunner.And("the cost for faculty 1 for the period 1 and year 2015 is", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "FacultyName",
                        "ProjectCost"});
            table3.AddRow(new string[] {
                        "Ingenieria",
                        "30"});
            table3.AddRow(new string[] {
                        "Ingenieria",
                        "10"});
#line 16
 testRunner.And("the cost for faculty 1 for the period 2 and year 2015 is", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "FacultyName",
                        "ProjectCost"});
            table4.AddRow(new string[] {
                        "Ingenieria",
                        "30"});
            table4.AddRow(new string[] {
                        "Ingenieria",
                        "10"});
#line 20
 testRunner.And("the cost for faculty 1 for the period 3 and year 2015 is", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "FacultyName",
                        "ProjectCost"});
            table5.AddRow(new string[] {
                        "Ingenieria",
                        "30"});
            table5.AddRow(new string[] {
                        "Ingenieria",
                        "10"});
#line 24
 testRunner.And("the cost for faculty 1 for the period 5 and year 2015 is", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "FacultyName",
                        "ProjectCost"});
            table6.AddRow(new string[] {
                        "Licenciatura",
                        "100"});
#line 28
 testRunner.And("the cost for faculty 2 for the period 1 and year 2015 is", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "FacultyName",
                        "ProjectCost"});
            table7.AddRow(new string[] {
                        "Licenciatura",
                        "100"});
#line 31
 testRunner.And("the cost for faculty 2 for the period 2 and year 2015 is", ((string)(null)), table7, "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "FacultyName",
                        "ProjectCost"});
            table8.AddRow(new string[] {
                        "Licenciatura",
                        "100"});
#line 34
 testRunner.And("the cost for faculty 2 for the period 3 and year 2015 is", ((string)(null)), table8, "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "FacultyName",
                        "ProjectCost"});
            table9.AddRow(new string[] {
                        "Licenciatura",
                        "100"});
#line 37
 testRunner.And("the cost for faculty 2 for the period 5 and year 2015 is", ((string)(null)), table9, "And ");
#line 40
 testRunner.When("I execute the faculties cost report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Facultad",
                        "Periodo 1",
                        "Periodo 2",
                        "Periodo 3",
                        "Periodo 5"});
            table10.AddRow(new string[] {
                        "Ingenieria",
                        "40",
                        "40",
                        "40",
                        "40"});
            table10.AddRow(new string[] {
                        "Licenciatura",
                        "100",
                        "100",
                        "100",
                        "100"});
#line 41
 testRunner.Then("the faculties cost report should be", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Hours report by faculties")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "FacultiesReports")]
        public virtual void HoursReportByFaculties()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Hours report by faculties", ((string[])(null)));
#line 46
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name"});
            table11.AddRow(new string[] {
                        "1",
                        "Ingenieria"});
            table11.AddRow(new string[] {
                        "2",
                        "Licenciatura"});
#line 47
testRunner.Given("I have this faculties", ((string)(null)), table11, "Given ");
#line 51
 testRunner.And("the year is 2015", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "FacultyName",
                        "ProjectHours"});
            table12.AddRow(new string[] {
                        "Ingenieria",
                        "70"});
            table12.AddRow(new string[] {
                        "Ingenieria",
                        "80"});
            table12.AddRow(new string[] {
                        "Ingenieria",
                        "50"});
            table12.AddRow(new string[] {
                        "Ingenieria",
                        "60"});
            table12.AddRow(new string[] {
                        "Ingenieria",
                        "95"});
            table12.AddRow(new string[] {
                        "Ingenieria",
                        "74"});
            table12.AddRow(new string[] {
                        "Ingenieria",
                        "76"});
            table12.AddRow(new string[] {
                        "Ingenieria",
                        "65"});
#line 52
 testRunner.And("the hours for faculty 1 for the year 2015 is", ((string)(null)), table12, "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "FacultyName",
                        "ProjectHours"});
            table13.AddRow(new string[] {
                        "Licenciatura",
                        "80"});
            table13.AddRow(new string[] {
                        "Licenciatura",
                        "95"});
            table13.AddRow(new string[] {
                        "Licenciatura",
                        "85"});
            table13.AddRow(new string[] {
                        "Licenciatura",
                        "84"});
#line 62
 testRunner.And("the hours for faculty 2 for the year 2015 is", ((string)(null)), table13, "And ");
#line 68
 testRunner.When("I execute the faculties hours report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Facultad",
                        "Horas"});
            table14.AddRow(new string[] {
                        "Ingenieria",
                        "570"});
            table14.AddRow(new string[] {
                        "Licenciatura",
                        "344"});
#line 69
 testRunner.Then("the faculties hour report should be", ((string)(null)), table14, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("projects number by a major per current period")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "FacultiesReports")]
        public virtual void ProjectsNumberByAMajorPerCurrentPeriod()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("projects number by a major per current period", ((string[])(null)));
#line 74
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "MajorId",
                        "Name",
                        "Faculty"});
            table15.AddRow(new string[] {
                        "1",
                        "1",
                        "Ing. Sistemas",
                        "1"});
            table15.AddRow(new string[] {
                        "2",
                        "2",
                        "Mecatronica",
                        "1"});
            table15.AddRow(new string[] {
                        "3",
                        "3",
                        "Ing. Civil",
                        "1"});
            table15.AddRow(new string[] {
                        "4",
                        "4",
                        "Lic. Admon",
                        "2"});
#line 75
 testRunner.Given("I have this majors", ((string)(null)), table15, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Number",
                        "Year",
                        "FromDate",
                        "ToDate",
                        "IsCurrent"});
            table16.AddRow(new string[] {
                        "1",
                        "1",
                        "2016",
                        "08/08/16",
                        "10/10/16",
                        "True"});
#line 81
 testRunner.And("This is the current period", ((string)(null)), table16, "And ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "MajorId",
                        "Major",
                        "Total"});
            table17.AddRow(new string[] {
                        "1",
                        "Ing. Sistemas",
                        "3"});
            table17.AddRow(new string[] {
                        "1",
                        "Ing. Sistemas",
                        "5"});
            table17.AddRow(new string[] {
                        "2",
                        "Mecatronica",
                        "4"});
            table17.AddRow(new string[] {
                        "3",
                        "Ing. Civil",
                        "3"});
            table17.AddRow(new string[] {
                        "3",
                        "Ing. Civil",
                        "2"});
            table17.AddRow(new string[] {
                        "4",
                        "Lic. Admon",
                        "3"});
#line 84
 testRunner.And("I have the majors and it has many projects", ((string)(null)), table17, "And ");
#line 92
 testRunner.When("I execute the projects by major report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Carrera",
                        "Proyectos"});
            table18.AddRow(new string[] {
                        "Ing. Sistemas",
                        "8"});
            table18.AddRow(new string[] {
                        "Mecatronica",
                        "4"});
            table18.AddRow(new string[] {
                        "Ing. Civil",
                        "5"});
            table18.AddRow(new string[] {
                        "Lic. Admon",
                        "3"});
#line 93
 testRunner.Then("I have the projects", ((string)(null)), table18, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("List all the projects that has been made in a class")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "FacultiesReports")]
        public virtual void ListAllTheProjectsThatHasBeenMadeInAClass()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("List all the projects that has been made in a class", ((string[])(null)));
#line 100
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Code",
                        "Class",
                        "Period",
                        "User"});
            table19.AddRow(new string[] {
                        "1",
                        "1",
                        "1",
                        "1"});
#line 101
 testRunner.Given("I have the section", ((string)(null)), table19, "Given ");
#line 104
 testRunner.And("The period is the number 1 of year 2016", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "ProjectId",
                        "Name",
                        "Description",
                        "IsDeleted",
                        "BeneficiarieOrganization"});
            table20.AddRow(new string[] {
                        "1",
                        "1",
                        "Vinculacion Unitec",
                        "Vinculacion Unitec",
                        "false",
                        "Unitec"});
            table20.AddRow(new string[] {
                        "2",
                        "2",
                        "Mhotivo",
                        "Mhotivo",
                        "false",
                        "Mhotivo"});
            table20.AddRow(new string[] {
                        "3",
                        "3",
                        "Proyecto CCIC",
                        "Proyecto CCIC",
                        "false",
                        "CCIC"});
#line 105
 testRunner.And("The class 1 has the projects", ((string)(null)), table20, "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "AccountId",
                        "Name",
                        "Password",
                        "Major",
                        "Campus",
                        "Email",
                        "CreationDate",
                        "ModificationDate",
                        "Finiquiteado",
                        "Status"});
            table21.AddRow(new string[] {
                        "1",
                        "1",
                        "Andrea",
                        "1234",
                        "1",
                        "SPS",
                        "andrea@gmail.com",
                        "08/08/16",
                        "10/10/16",
                        "False",
                        "Active"});
#line 110
 testRunner.And("The list of professors is", ((string)(null)), table21, "And ");
#line 113
 testRunner.When("I execute the list projects by class report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "IdProyecto",
                        "Nombre",
                        "Beneficiario",
                        "Maestro",
                        "Periodo",
                        "Anio"});
            table22.AddRow(new string[] {
                        "1",
                        "Vinculacion Unitec",
                        "Unitec",
                        "Andrea",
                        "1",
                        "2016"});
            table22.AddRow(new string[] {
                        "2",
                        "Mhotivo",
                        "Mhotivo",
                        "Andrea",
                        "1",
                        "2016"});
            table22.AddRow(new string[] {
                        "3",
                        "Proyecto CCIC",
                        "CCIC",
                        "Andrea",
                        "1",
                        "2016"});
#line 114
 testRunner.Then("The result should be", ((string)(null)), table22, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
