// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace VinculacionBackend.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class HourNumberReportFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "HourNumberReport.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HourNumberReport", "\tIn order to know the amount of hours done in a year\r\n\tAs manager\r\n\tI want to be " +
                    "told the amount of hours in each period", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "HourNumberReport")))
            {
                VinculacionBackend.Specs.HourNumberReportFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("All classes have hours done")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "HourNumberReport")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("reports")]
        public virtual void AllClassesHaveHoursDone()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All classes have hours done", new string[] {
                        "reports"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table1.AddRow(new string[] {
                        "10",
                        "30",
                        "20",
                        "40"});
#line 8
 testRunner.Given("the amount of hours for Class \'Inglés\' and year 2015 is", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table2.AddRow(new string[] {
                        "10",
                        "30",
                        "20",
                        "40"});
#line 11
 testRunner.And("the amount of hours for Class \'Ofimática\' and year 2015 is", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table3.AddRow(new string[] {
                        "10",
                        "30",
                        "20",
                        "40"});
#line 14
 testRunner.And("the amount of hours for Class \'Sociología\' and year 2015 is", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table4.AddRow(new string[] {
                        "10",
                        "30",
                        "20",
                        "40"});
#line 17
 testRunner.And("the amount of hours for Class \'Filosofía\' and year 2015 is", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table5.AddRow(new string[] {
                        "10",
                        "30",
                        "20",
                        "40"});
#line 20
 testRunner.And("the amount of hours for Class \'Ecología\' and year 2015 is", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table6.AddRow(new string[] {
                        "10",
                        "30",
                        "20",
                        "40"});
#line 23
 testRunner.And("the amount of hours for Faculty 1 and year 2015 is", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table7.AddRow(new string[] {
                        "10",
                        "30",
                        "20",
                        "40"});
#line 26
 testRunner.And("the amount of hours for Faculty 2 and year 2015 is", ((string)(null)), table7, "And ");
#line 29
 testRunner.And("the hours year is 2015", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.When("I execute the hour number report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "StudentNumber",
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table8.AddRow(new string[] {
                        "Inglés",
                        "10",
                        "30",
                        "20",
                        "40"});
            table8.AddRow(new string[] {
                        "Ofimática",
                        "10",
                        "30",
                        "20",
                        "40"});
            table8.AddRow(new string[] {
                        "Sociología",
                        "10",
                        "30",
                        "20",
                        "40"});
            table8.AddRow(new string[] {
                        "Filosofía",
                        "10",
                        "30",
                        "20",
                        "40"});
            table8.AddRow(new string[] {
                        "Ecología",
                        "10",
                        "30",
                        "20",
                        "40"});
            table8.AddRow(new string[] {
                        "FIA",
                        "10",
                        "30",
                        "20",
                        "40"});
            table8.AddRow(new string[] {
                        "FCAS",
                        "10",
                        "30",
                        "20",
                        "40"});
            table8.AddRow(new string[] {
                        "Total",
                        "70",
                        "210",
                        "140",
                        "280"});
#line 31
 testRunner.Then("the hour number report should be", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("All classes have no hours done")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "HourNumberReport")]
        public virtual void AllClassesHaveNoHoursDone()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All classes have no hours done", ((string[])(null)));
#line 42
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table9.AddRow(new string[] {
                        "0",
                        "0",
                        "0",
                        "0"});
#line 43
 testRunner.Given("the amount of students for Class \'Inglés\' and year 2015 is", ((string)(null)), table9, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table10.AddRow(new string[] {
                        "0",
                        "0",
                        "0",
                        "0"});
#line 46
 testRunner.And("the amount of students for Class \'Ofimática\' and year 2015 is", ((string)(null)), table10, "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table11.AddRow(new string[] {
                        "0",
                        "0",
                        "0",
                        "0"});
#line 49
 testRunner.And("the amount of students for Class \'Sociología\' and year 2015 is", ((string)(null)), table11, "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table12.AddRow(new string[] {
                        "0",
                        "0",
                        "0",
                        "0"});
#line 52
 testRunner.And("the amount of students for Class \'Filosofía\' and year 2015 is", ((string)(null)), table12, "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table13.AddRow(new string[] {
                        "0",
                        "0",
                        "0",
                        "0"});
#line 55
 testRunner.And("the amount of students for Class \'Ecología\' and year 2015 is", ((string)(null)), table13, "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table14.AddRow(new string[] {
                        "0",
                        "0",
                        "0",
                        "0"});
#line 58
 testRunner.And("the amount of students for Faculty 1 and year 2015 is", ((string)(null)), table14, "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table15.AddRow(new string[] {
                        "0",
                        "0",
                        "0",
                        "0"});
#line 61
 testRunner.And("the amount of students for Faculty 2 and year 2015 is", ((string)(null)), table15, "And ");
#line 64
 testRunner.And("the current year is 2015", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
 testRunner.When("I execute the student count report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "StudentNumber",
                        "FirstPeriod",
                        "SecondPeriod",
                        "FourthPeriod",
                        "FifthPeriod"});
            table16.AddRow(new string[] {
                        "Inglés",
                        "0",
                        "0",
                        "0",
                        "0"});
            table16.AddRow(new string[] {
                        "Ofimática",
                        "0",
                        "0",
                        "0",
                        "0"});
            table16.AddRow(new string[] {
                        "Sociología",
                        "0",
                        "0",
                        "0",
                        "0"});
            table16.AddRow(new string[] {
                        "Filosofía",
                        "0",
                        "0",
                        "0",
                        "0"});
            table16.AddRow(new string[] {
                        "Ecología",
                        "0",
                        "0",
                        "0",
                        "0"});
            table16.AddRow(new string[] {
                        "FIA",
                        "0",
                        "0",
                        "0",
                        "0"});
            table16.AddRow(new string[] {
                        "FCAS",
                        "0",
                        "0",
                        "0",
                        "0"});
            table16.AddRow(new string[] {
                        "Total",
                        "0",
                        "0",
                        "0",
                        "0"});
#line 66
 testRunner.Then("the student count report should be", ((string)(null)), table16, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
